### ISSUE TITLE
Investigate: Repeating event

### ISSUE THREAD

**Issue by nualn** [Ohtuprojekti-Fintraffic/lentovaraukset#101]

**Comment by antonlep** [comment]
Kaksi vaihtoehtoa:  Käyttää recurring event - sääntöjä jotka tallennetaan, tai tallentaa luodut aikaikkunat yksittäisinä aikoina tietokantaan

### Recurring event
- rrule pluginilla voi tehdä toistuvia sääntöjä (https://fullcalendar.io/docs/rrule-plugin)
- ei ole yksiselitteistä tapaa miten säännöt kannattaa tallentaa tietokantaan. Jos sääntöä muokataan yksittäisen päivän osalta (aikaa muutetaan tai poistetaan), tämä tallennetaan yksittäisenä poikkeuksena. Jos koko sääntöä muutetaan, voidaan esim tallentaa uusi sääntö joka ylikirjoittaa vanhan säännön tulevaisuuden aikojen osalta.
- rakenteesta voi tulla monimutkainen, vanhojen sääntöjen ja poikkeusten käsittely pitää miettiä
- varausaikojen ja saatavilla olevien aikojen vertailu voi olla haastavaa (varausaikaa tulee verrata sekä toistuviin aikasääntöihin että yksittäisesti määritettyihin aikaikkunoihin)

### Aikojen tallennus yksittäisinä aikaikkunoina
- Suoraviivainen toteutus: kun sääntöä muokataan niin aikaikkunat tallennetaan tietokantaan (samalla aiemmat ajat poistetaan)
- Vie aavistuksen verran enemmän tilaa tietokannassa (esim sääntö vuodeksi eteenpäin = 365 ylimäräistä riviä tietokannassa), säännön päivitys voi ottaa hieman enemmän aikaa
- Ei voi tehdä monipuolisia toistumissääntöjä

### Esimerkki toteutus hahmotelma

![Image](https://user-images.githubusercontent.com/76871257/218441194-42d726c5-403e-44cd-a7d1-326a239234b9.png)

- Toistuva sääntö on lentokenttäkohtainen
- Yksi sääntö kerrallaan voimassa / lentokenttä
- Määritetään joka viikonpäivälle erikseen (sama sääntö toistuu joka viikko)
- Kun sääntöä muutetaan, kaikki tulevaisuudessa olevat aikaikkunat poistetaan ja säännön mukaiset uudet lisätään (esim vuodeksi eteenpäin)

### Tarvitaanko aikaikkunoiden ja varausten välistä kytkentää?

- Nämä kytkennät pitäisi päivittää aina kun aikaikkunat muuttuvat. Tarviiko kytkentää välttämättä olla?
