### ISSUE TITLE
Zod validointiin varmistus, etteivät fieldit ole tyhjiä

### ISSUE THREAD

**Issue by vaisest** [Ohtuprojekti-Fintraffic/lentovaraukset#214]

**Comment by Jokauppi** [comment]
Tällä hetkellä frontendin ja backendin zod-validointi ei tarkista, että vaaditut kentät todella sisältävät jotain tietoa, vaan kenttiin on mahdollista tallentaa tyhjiä merkkijonoja. Myös undefinedin tallentaminen antaa errorin vasta tietokannan tasolta.
